from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path

from .project import PROJECT_ROOT, env_path, normalize_path


@dataclass(frozen=True)
class DemoRuntimeConfig:
    project_root: Path
    output_dir: Path
    features_path: Path
    shap_path: Path
    geo_path: Path


def build_demo_runtime_config() -> DemoRuntimeConfig:
    output_dir = env_path("TERRA_IA_OUTPUT_DIR", PROJECT_ROOT)
    return DemoRuntimeConfig(
        project_root=PROJECT_ROOT,
        output_dir=output_dir,
        features_path=env_path("TERRA_IA_FEATURES_PATH", output_dir / "features_parcelles_v6.csv"),
        shap_path=env_path("TERRA_IA_SHAP_PATH", output_dir / "shap_par_parcelle_v6.csv"),
        geo_path=env_path(
            "TERRA_IA_GEO_PATH",
            PROJECT_ROOT / "data" / "lidar_chamberey" / "parcelles_73065.geojson",
        ),
    )


def demo_env_updates_from_args(args: argparse.Namespace) -> dict[str, str]:
    env_updates: dict[str, str] = {}
    base = build_demo_runtime_config()

    output_dir = normalize_path(args.output_dir) if args.output_dir else base.output_dir
    features_path = normalize_path(args.features) if args.features else (
        output_dir / "features_parcelles_v6.csv" if args.output_dir else base.features_path
    )
    shap_path = normalize_path(args.shap) if args.shap else (
        output_dir / "shap_par_parcelle_v6.csv" if args.output_dir else base.shap_path
    )
    geo_path = normalize_path(args.geo) if args.geo else base.geo_path

    env_updates["TERRA_IA_OUTPUT_DIR"] = str(output_dir)
    env_updates["TERRA_IA_FEATURES_PATH"] = str(features_path)
    env_updates["TERRA_IA_SHAP_PATH"] = str(shap_path)
    env_updates["TERRA_IA_GEO_PATH"] = str(geo_path)
    return env_updates


def missing_demo_assets(config: DemoRuntimeConfig) -> list[tuple[str, Path, str]]:
    required_assets = [
        (
            "Features dataset",
            config.features_path,
            "Generated by the pipeline and required for all scoring pages.",
        ),
        (
            "Parcel geometry",
            config.geo_path,
            "Required to render the cadastre map in the live demo.",
        ),
    ]
    return [(label, path, reason) for label, path, reason in required_assets if not path.exists()]


def recommended_setup_commands() -> str:
    return (
        "conda env create -f environment.yml\n"
        "conda activate terra-ia-capstone\n"
        "python preflight.py\n"
        "python pipeline.py\n"
        "python demo.py"
    )
