from __future__ import annotations

from pathlib import Path
from typing import Mapping, Sequence


def build_ml_dataset_readme(
    *,
    output_csv_ml_v6: Path,
    feat_cols: Sequence[str],
    feature_groups: Mapping[str, Sequence[str]],
    grid_size_m: int,
    shap_filename: str = "shap_par_parcelle_v6.csv",
    generated_from: str = "python pipeline.py",
) -> str:
    feature_lines = "\n".join(
        f"  {feature:35s} [{next((group for group, items in feature_groups.items() if feature in items), '?')}]"
        for feature in feat_cols
    )

    return f"""# Terra-IA - ML Dataset V6 README

## Version : v6.0
## File : {output_csv_ml_v6.name}
Generated by `{generated_from}` - April 2026

## Available features ({len(feat_cols)})
```
{feature_lines}
```

## Target column : proxy_label
  1  = likely constructible  (H1 LiDAR + H3 DVF when available)
  0  = constrained           (H2 LiDAR + H4 DVF when available)
  -1 = ABSTAIN (excluded from this ML dataset)

## Compatibility columns
`CPI_v3` is the historical deterministic baseline score [0-100]. It remains in the V6 CSV schema so existing notebooks, SHAP exports, and the demo stay compatible.

`CPI_ML_v3` is the historical ML score name used in the full parcel export. The SHAP parcel file also exposes V6-friendly aliases (`CPI_ML_v6`, `CPI_v6`) for presentation.

## Spatial block column
`block_id` identifies the {grid_size_m}m spatial grid block and must be used for GroupKFold validation.

## Recommended model - XGBoost LambdaMART
```python
import xgboost as xgb
import numpy as np

# Sort by spatial block for LambdaMART
df_sorted = df.sort_values('block_id')
X = df_sorted[FEAT_COLS].values
y = df_sorted['proxy_label'].values

_, qid_inv = np.unique(df_sorted['block_id'], return_inverse=True)
_, counts  = np.unique(qid_inv, return_counts=True)

model = xgb.XGBRanker(
    objective='rank:ndcg',
    n_estimators=300,
    max_depth=4,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)
model.fit(X, y, group=counts)
```

## Cross-validation - spatial GroupKFold required
```python
from sklearn.model_selection import GroupKFold

gkf = GroupKFold(n_splits=5)
for tr_idx, val_idx in gkf.split(X, y, groups=df['block_id']):
    blocks_tr = df['block_id'].values[tr_idx]
    _, qid_tr = np.unique(blocks_tr, return_inverse=True)
    sort_idx  = np.argsort(qid_tr)
    _, cnts   = np.unique(qid_tr[sort_idx], return_counts=True)
    model.fit(X[tr_idx][sort_idx], y[tr_idx][sort_idx], group=cnts)
    scores = model.predict(X[val_idx])
```

## Target metrics (priority order)
  1. NDCG@20       - ranking quality
  2. Precision@20  - top-k business relevance
  3. AUC-ROC       - overall discrimination
  4. Spearman vs CPI_v3 - coherence with the deterministic baseline

## SHAP explainability
```python
import shap
explainer   = shap.TreeExplainer(model)
shap_values = explainer.shap_values(X)
```

## Modeling cautions
  - Do not use `surface_m2` as an ML feature because it is redundant with the weak labels.
  - Check class distribution by spatial block before cross-validation.
  - XGBRanker requires sorting by `block_id` before fit().
  - Perfect RF metrics can indicate feature/label redundancy, especially when DVF is unavailable.

## Parcel-level SHAP file : {shap_filename}
Columns : id_parcelle, shap_slope_p50, shap_slope_p90, ...,
           shap_groupe_SLOPE, shap_groupe_HYDROLOGY,
           shap_groupe_MORPHOLOGY, shap_groupe_SUNLIGHT,
           CPI_ML_v6, CPI_v6, CPI_technique

## References
  LambdaMART   : Chen & Guestrin (2016) XGBoost - KDD 2016
  SHAP         : Lundberg & Lee (2017) NeurIPS 30
  Spatial CV   : Valavi et al. (2019) Methods Ecol Evol 10(2):225-232
  Snorkel      : Ratner et al. (2017) VLDB Journal 26:793-817
  Burges       : Burges et al. (2006) Learning to Rank - ICML
"""
